### ISSUE TITLE
odr-dab-mux to easydab v2 card - connection optimization

### ISSUE THREAD

**Issue by chicco64** [colisee/rpi-dab-tx#4]
Hi !
I am writing to you because I believe you have an excellent experience in DAB installation !
I would like to understand if it is possible to optimize the connection between odr-dab-mux (currently virtualized in the datacenter) and the easydab v2 card.
I am currently connected via ZeroMQ (latency 55ms) but I often find disconnections, I think due to insufficient buffer of the easydab v2 card.
Do you think it's possible? Can you help me ? thank you

**Comment by colisee** [comment]
Hi chicco64,

I am not a fan of ZeroMQ, for I had performance issues when running it between odr-DabMux and odr-DabMod (unlike you, I don't have an easydab v2 card) on a Raspberry PI 3b.

Did you try **raw ETI for tcp**? If you are using port 18081, then the outputs section of the mux configuration file should look like:
```
outputs {
    net "tcp://*:18081"
}
```
Good luck.

**Comment by chicco64** [comment]
Hi ! many thanks for your answer...
sorry, but don't work...
my card it can only work like this:

outputs {
    zmq  "zmq+tcp://*:9200"
    throttle "simul://"
    }

the problem is that the card should have a larger buffer to support in the line.
If I use the encoder-manager on the virtualized server (datacenter) while the multiplexer is built on a raspberry (only the multplexer is activated) and connected directly through the local LAN to the easy-dab board, there is no problem !
But I have to open all the multiplexer ports on the public network to receive the stream from the server, this is the inconvenience!
Do you have any idea?

**Comment by colisee** [comment]
Hi,

The multiplex (odr-dabmux) is the center-piece of the transmission chain. 

- odr-audioenc encoders send their data to the designated ports of the host where odr-dabmux is running (in your case the RPI)
- The modulator (in your case easydab v3) reads from the designated port on the host where odr-dabmux is running

If you have disconnections, it could also come from the RPI not powerful enough to handle in and out communication flows…

What if you moved the multiplex (odr-dabmux) to the data center (this way you do not expose the ports related to the encoders) and reconfigure the easydab card to get the multiplex data from the data center?

Kind regards.

**Comment by colisee** [comment]
When reading again your last post, I realize that my reply might not be appropriate. 
Can you confirm that the disconnections issues on the easydab card occur when both encoders and multiplex are at the data center?

**Comment by chicco64** [comment]
Yes, that's right, I can confirm this.
The problem is the latency between the datacenter and the easydabv2 card
unfortunately we have 48 ms of latency...
We are on the edge !
Already with 55 ms of latency the connection is not stable.
at this moment both the encoder and the multiplex are both in the datacenter

**Comment by colisee** [comment]
Got it!
Then, I can only see 1 possible way to make it work with the multiplex at the data center: replace ZMQ with eti-over-tcp. 

1. change the outputs section of your multiplex configuration file as follows
   ```
   outputs {
       net "tcp://*:9200"
   }
   ```
1. On the easydab card, deselect the « enable ZeroMQ Client Handshake » and maybe deselect « No Delayed TCP ACK ». Hopefully there is a documentation on the easydab that explains how to setup the card for ETI-over-tcp. 

Please let me know if this solves the issue.

**Comment by chicco64** [comment]
Hi !
easydab can connect as you proposed but with the following modification

outputs {
    net "tcp://*:9200"
    throttle "simul://"
}

Unfortunately, however, the change is pejorative, in the sense that the instability increases with respect to zeroMQ.

**Comment by colisee** [comment]
Sorry to read that it didn’t solve the issue: I really thought that ZeroMQ was the culprit, because I had performance issues with it when I started with this repository. 

I am afraid I can’t help you further…
