### ISSUE TITLE
Multiplexer-Manager does not update the "odr-dabmux.info" file

### ISSUE THREAD

**Issue by chicco64** [colisee/rpi-dab-tx#5]
Hi,
thanks to your script, I discovered the interesting "Multiplexer-Manager" functionality.
However, I noticed that it is not possible to update the "odr-dabmux.info" file by editing it.
In practice, you can only view but not edit anything.
I don't know if the fact is intentional or there is some problem with the file permissions.
<img width="405" alt="mux_man2" src="https://user-images.githubusercontent.com/59960414/157114145-8d97dd88-df1f-4ed8-b3ba-e1bb2c9f1749.PNG">
You could verify ? Many thanks

**Comment by colisee** [comment]
Hi,

Currently, the multiplex-manager is still at an early development stage. It can only update some parameters (those in the rc param) in the running job **without updating the configuration file**. 

I started to wok on the enhancement of the multiplex-manager, but I am also working on some other tasks. Thus, you need to be a little patient…

By the way, this repository will soon be dropped in favor of Opendigitalradio/dab-scripts (you can have a look at the **next** branch).
